spring:
  datasource:
    url: jdbc:log4jdbc:h2:tcp://localhost/~/lsy;MODE=mySQL
    username: sa
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

server:
  port: 8888

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: study.thyemeleaflayoutstudy1.domain.vo

